version: "3"

vars:
  WORKSPACE_PATH:
    sh: 'if [ -n "$WSL_DISTRO_NAME" ]; then wslpath -aw .; else pwd; fi'

tasks:
  default:
    desc: Show available commands
    cmds:
      - task --list

  io:
    desc: Print nix flake inputs and outputs
    cmds:
      - nix flake metadata
      - nix flake show

  update:
    desc: Update nix flake
    cmds:
      - nix flake update

  lint:
    desc: Lint nix files
    cmds:
      - nix fmt

  check:
    desc: Check nix flake
    cmds:
      - nix flake check

  dev:
    desc: Manually enter dev shell
    cmds:
      - nix develop

  build:
    desc: Build nix flake
    deps: [lint, check]
    cmds:
      - nix build

  clean:
    desc: Remove build output link
    cmds:
      - rm -f ./result

  run:
    desc: Run nix flake to setup environment
    deps: [lint, check]
    cmds:
      - nix run

  activate:home:
    desc: Activates nix home-configuration
    cmds:
      - nix run --show-trace .#activate $USER@

